### ISSUE TITLE
Problem after calling soft reset (ESP.Restart())

### ISSUE THREAD

**Issue by mad-b** [shurillu/CTBot#51]
Hello.
I am making one of the commanbs to b e a reset command - a simple "reset" token that you can send from the telegram chat, to... soft reset the ESP8266.
So, I write "reset" on the chat, send and it receives and restarts the ESP - as expected.

However, it enters an endless restart loop like if the last "reset" command keeps in the messages in put queue somehow, and soon after the soft restart, it ends up in the if-else containing the "reset" and restarts all over - and over and over ...

Is there some issue, like I should wait clear or check something before reset, to avoid leftovers of some sort inside the system?

Can you enlight me about what can be happening and how to solve this?
Thanks

**Comment by ivan140** [comment]
Hi,

Had the same issue with ESP 8266. My workaround was:

- after receiving the reset command setting the text in the message to some other not resetting command: ' '
- saving the fact, that you just resetet to EEPROM
- adding some delay before calling the actual ESP.restart()

```        
else if (m.text.indexOf("/reset") > -1) {
                m.text = "";
                if (!config.justResetet) {
                  bot.sendMessage(m, "reset");
                  config.justResetet = true;
                  EEPROM.put(0, config);
                  EEPROM.commit();
                  delay(3000);
                  ESP.restart();
                } else {
                  config.justResetet = false;
                  EEPROM.put(0, config);
                  EEPROM.commit();
                }
}
```

**Comment by shurillu** [comment]
Hello mad-b, hello ivan140,

  the issue is relate to the method how Telegram knows if a message is corrected collected or not.
Everytime a `getNewMessage()` method is called, it send to the Telegram server the last received message, so the Telegram server knows that message is corrected received and send all the new messages.
Going back to your issue, this simple trick will resolve the problem: before calling the `ESP.restart()`, call the `getNewMessage()` method to confirm the reset message is arrived. 
You don't need to handle the message (if any) fetched by the `getNewMessage()` because it will not be confirmed so after the reset, it will be fetched one more time.
Try this:
```
#include "CTBot.h"
CTBot myBot;
String ssid  = "mySSID"    ; // REPLACE mySSID WITH YOUR WIFI SSID
String pass  = "myPassword"; // REPLACE myPassword YOUR WIFI PASSWORD, IF ANY
String token = "myToken"   ; // REPLACE myToken WITH YOUR TELEGRAM BOT TOKEN
void setup() {
	Serial.begin(115200);
	Serial.println("Starting TelegramBot...");
	myBot.wifiConnect(ssid, pass);
	myBot.setTelegramToken(token);
}
void loop() {
	TBMessage msg;
	if (myBot.getNewMessage(msg)) {
     if (msg.text.equalsIgnoreCase("restart")) {
        myBot.getNewMessage(msg); // confirm the restart message is received
        ESP.restart();
     } else 
	      myBot.sendMessage(msg.sender.id, msg.text);
	}	 
	delay(500);
}
```

**Comment by mad-b** [comment]
Thanks for the info, Stefano. I was suspecting it was something of the sort :)
